### ISSUE TITLE
sample code doesn't work

### ISSUE THREAD

**Issue by dcaud** [MrFlick/myphone#1]
Can you let me know if I can help? Here's the error I get after running the sample code:

Error in rsqlite_connect(dbname, loadable.extensions, flags, vfs) : 
  Could not connect to database:
unable to open database file
Called from: rsqlite_connect(dbname, loadable.extensions, flags, vfs)

**Comment by MrFlick** [comment]
I recently learned that the backup file format changed in the latest iOS update. I'm working on a branch now to fix those changes (and clean things up a bit). The branch isn't quite ready to publish yet, but you can test it with 

    devtools::install_github("MrFlick/myphone", ref="ios10")

Not that the functions did change slightly so check that out and I've started adding some documentation as well.

**Comment by dcaud** [comment]
Great. The below produces a dataframe (called SMS) with some basic SMS message data:

devtools::install_github("MrFlick/myphone", ref="ios10")

require(myphone)
backups <- get_backup();

if ( length(backups)>0 ) {
  sms <- read_sms_data(backups);
  
} else {
  print("No backups found!");
}

**Comment by dcaud** [comment]
Now I'm trying to figure out how to merge other data with the SMS dataframe (most important is contact info, so that sender names are visible; second most important is to be able to render the attachments).

Thanks again for your package.

**Comment by MrFlick** [comment]
You can get contacts with

    contacts <- read_contacts(backup)
    # note you may need to re-install the dev branch because there 
    # was a bug in this function i fixed this morning

and then merge them with

    merged <- left_join(sms, contacts, by="contact")

You can get the file path to attachments with

    sms_attachment_path(backup, na.omit(sms$attachment_filename))

This package is still pretty rough at this point but I hope to keep making improvements.

**Comment by dcaud** [comment]
read_contacts works as expected (after I took your advice and reinstalled).

The merge kinda works, but duplicates causes a one-to-many merge that isn't desirable. I think the cause is that the sanitize_phone_number function at the end of read_contacts isn't working properly.

**Comment by dcaud** [comment]
De-duping may also provide something desirable:

contacts <- read_contacts(backup)
contacts <- contacts[!duplicated(contacts$contact),]

**Comment by MrFlick** [comment]
Did you have duplicates in your address book? Or did the sanitize_phone_number function produce the same output for two different inputs? I haven't yet found a better way to link the SMS and Contact data. All I know is that this works with my own data. So if you can provide suggestions for improvements or examples of problems I would appreciate it.

**Comment by dcaud** [comment]
I have duplicates in my address book. 

I think removing duplicates in the contact book makes the merge work well -- I guess this all depends on what you want myphone to do. I'm using it to create a print out of my SMS messages (as a readable backup). 

Please ignore my note about sanitize_phone_number, it is now working correctly here.
